name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: checkout
      uses: actions/checkout@v3 # 将代码拷贝到虚机中
    
    - name: Install and build
      run: |
        npm install
        npm run build

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        token: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
        branch: gh-pages # 存放产物的分支名称
        folder: dist # 存放build后产物的目录
